repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    - id: python-bandit-vulnerability-check
      args: [-ll, --recursive, -x, tests]
      files: .py$
  - repo: local
    hooks:
    - id: tests
      name: run tests
      entry: pytest -v
      pass_filenames: false
      language: python
      types: [python]
      stages: [push]
