name: Python package
on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: check git branch
        run: |
          BRANCH=$(git branch | grep \*)
          if [ $BRANCH != "release" ]; then
            exit 1
          fi
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
