name: Publish

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Get master HEAD tag
      run: echo "RELEASE_HEAD_TAG=$(git tag --points-at HEAD)" >> $GITHUB_ENV
    - name: Stop if not master HEAD
      run: exit 1
      if: endsWith(github.ref, env.RELEASE_HEAD_TAG) != true
  publish:
    runs-on: ubuntu-latest
    needs: check-branch
    steps:
    - uses: actions/checkout@v3
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.16
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
