name: Quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Black Code Formatter
      uses: jpetrucciani/black-check@master
    - name: Flake8 Showstopper Linter
      uses: cclauss/Find-Python-syntax-errors-action@master
    - name: Flake8 Style Linter
      uses: jonasrk/flake8-action@master
      with:
        args: "--count --exit-zero --max-complexity=10 --max-line-length=88 --statistics"
    - name: Bandit Security Linter
      uses: jpetrucciani/bandit-check@master
