name: Tests

on:
  push:
  pull_request:
    branches: [master]
    types: [opened, reopened, ready_for_review, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8.16', '3.9.16', '3.10.10', '3.11.2']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry tox tox-gh-actions
    - name: Test with tox
      run: tox
